swagger: "2.0"
info:
  title: Pokemon API
  description: An over-engineered API doing stuff related to pokemons  
  version: '0.1'
host: localhost:8080
basePath: "/api"

tags:
  - name: pokemon
    description: Some stuff about pokemons
  - name: app
    description: Application endpoints
paths:
  /poke:

    get:
      tags:
        - "pokemon"
      description: Get a list of pokemons with "averageStat" calculated
      responses:
        "200":
          description: A list of pokemons
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PokemonListItem" 
  /poke/{pokeName}:
    get:
      tags:
        - "pokemon"
      description: Get a pokemon by name
      responses:
        "200":
          description: One pokemon with some auto-calculated attribuets
          schema:
            type: "object"
            $ref: "#/definitions/Pokemon" 
        "404":
          description: The pokemon was not found
          schema:
            type: "object"
            $ref: "#/definitions/NotFoundError"
  /health:
    get:
      tags:
        - "app"
      responses:
        "200":
          description: The application is healty and might be ready for receiving requests (this doesn't mean that it's ready!)
          schema:
            type: object
            properties:
              status: 
                type: string
                example: "ok"
              statusCode: 
                type: integer
                format: int32
                example: 200


definitions:
  # DISCLAIMER: This object was object was autogenerated using: https://roger13.github.io/SwagDefGen/
  # A better way to do it is either to generate it from TS interfaces using some plugins, or by defining it manually
  PokemonListItem:
    type: object
    properties: 
      name: 
        type: string
        example: spearow
      height: 
        type: integer
        format: int32
        example: 3
      base_experience: 
        type: integer
        format: int32
        example: 52
      id: 
        type: integer
        format: int32
        example: 21
      sprite_img: 
        type: string
        example: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png
      species: 
        type: object
        properties: 
          name: 
            type: string
            example: spearow
          url: 
            type: string
            example: https://pokeapi.co/api/v2/pokemon-species/21/
      url: 
        type: string
        example: https://pokeapi.co/api/v2/pokemon/21
      stats: 
        type: array
        items: 
          type: object
          properties: 
            base_stat: 
              type: integer
              format: int32
              example: 40
            effort: 
              type: integer
              format: int32
              example: 0
            stat: 
              type: object
              properties: 
                name: 
                  type: string
                  example: hp
                url: 
                  type: string
                  example: https://pokeapi.co/api/v2/stat/1/
      averageStat: 
        type: number
        example: 43.666666666666664
  Pokemon:
    type: object
    properties:
      name: 
        type: string
        example: bulbasaur
      height: 
        type: integer
        format: int32
        example: 7
      base_experience: 
        type: integer
        format: int32
        example: 64
      id: 
        type: integer
        format: int32
        example: 1
      sprite_img: 
        type: string
        example: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
      species: 
        type: object
        properties: 
          name: 
            type: string
            example: bulbasaur
          url: 
            type: string
            example: https://pokeapi.co/api/v2/pokemon-species/1/
      url: 
        type: string
        example: https://pokeapi.co/api/v2/pokemon/1
      stats: 
        type: array
        items: 
          type: object
          properties: 
            base_stat: 
              type: integer
              format: int32
              example: 45
            effort: 
              type: integer
              format: int32
              example: 0
            stat: 
              type: object
              properties: 
                name: 
                  type: string
                  example: hp
                url: 
                  type: string
                  example: https://pokeapi.co/api/v2/stat/1/
      averageStat: 
        type: integer
        format: int32
        example: 53

  NotFoundError:
    type: object
    properties:
      status: 
        type: integer
        format: int32
        example: 404
      type: 
        type: string
        example: NOT_FOUND
      title: 
        type: string
        example: The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
      detail: 
        type: string
        example: The Pokemon with the name pikatchu is not found
      instance: 
        type: string
        example: pokemon/pikatchu
